In [18]:
import sys
!{sys.executable} -m pip install --upgrade nbformat ipython

Requirement already satisfied: nbformat in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (5.10.4)
Requirement already satisfied: ipython in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (9.10.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nbformat) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from ipython) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from ipython) (0.6.3)
Requirement already satisfied: wcwidth in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from jedi>=0.18.1->ipython) (0.8.6)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.29.0)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\Rajvardhan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: executing>=1.2.0 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\Rajvardhan\AppData\Roaming\Python\Python313\site-packages (from stack_data>=0.6.0->ipython) (0.2.3)

In [19]:
import plotly.io as pio
pio.renderers.default = "vscode"

In [20]:
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()

In [21]:
# plotly = > data visulaization library like seaborn and matplotlib
# it has 3 things

# 1.plotly express => create chart with few line
# 2.plotly parph objects => create charts with more control
# 3.plotly dash => can build the real world web app

In [22]:
"""
What Plotly actually is

Plotly is a library for interactive data visualization.

Unlike static charts (Matplotlib):

You can hover to see values

Zoom & pan

Toggle traces on/off

Embed charts in web apps & dashboards

Think of Plotly charts as mini web apps, not images.

Plotly’s ecosystem (important)

Plotly isn’t just one thing — it’s three layers:

1️⃣ Plotly Express (high-level)

Fastest way to make charts

One function = one chart

Perfect for beginners

Example mindset:

“I have a DataFrame → I want a chart now.”

You’ll spend most of your early time here.

2️⃣ Plotly Graph Objects (low-level)

More verbose

Full control

Needed for complex charts

Mindset:

“I want to control every detail.”

3️⃣ Dash (web apps)

Turns Plotly charts into interactive dashboards

Used for real products, not just notebooks

Mindset:

“Other people will use this.”

How Plotly is different from Matplotlib
Feature	Matplotlib	Plotly
Interactivity	❌	✅
Hover info	❌	✅
Zoom & pan	❌	✅
Web-ready	❌	✅
Learning curve	Easy	Medium

Key shift:

Matplotlib draws images. Plotly builds objects.

What a Plotly chart really is

A Plotly chart is:

Data (your DataFrame)

Traces (lines, bars, points)

Layout (titles, axes, legend)

You don’t “draw” — you configure.

Installation (do this once)
pip install plotly

Optional but common:

pip install pandas
"""

'\nWhat Plotly actually is\n\nPlotly is a library for interactive data visualization.\n\nUnlike static charts (Matplotlib):\n\nYou can hover to see values\n\nZoom & pan\n\nToggle traces on/off\n\nEmbed charts in web apps & dashboards\n\nThink of Plotly charts as mini web apps, not images.\n\nPlotly’s ecosystem (important)\n\nPlotly isn’t just one thing — it’s three layers:\n\n1️⃣ Plotly Express (high-level)\n\nFastest way to make charts\n\nOne function = one chart\n\nPerfect for beginners\n\nExample mindset:\n\n“I have a DataFrame → I want a chart now.”\n\nYou’ll spend most of your early time here.\n\n2️⃣ Plotly Graph Objects (low-level)\n\nMore verbose\n\nFull control\n\nNeeded for complex charts\n\nMindset:\n\n“I want to control every detail.”\n\n3️⃣ Dash (web apps)\n\nTurns Plotly charts into interactive dashboards\n\nUsed for real products, not just notebooks\n\nMindset:\n\n“Other people will use this.”\n\nHow Plotly is different from Matplotlib\nFeature\tMatplotlib\tPlotly\nInteractivity\t❌\t✅\nHover info\t❌\t✅\nZoom & pan\t❌\t✅\nWeb-ready\t❌\t✅\nLearning curve\tEasy\tMedium\n\nKey shift:\n\nMatplotlib draws images. Plotly builds objects.\n\nWhat a Plotly chart really is\n\nA Plotly chart is:\n\nData (your DataFrame)\n\nTraces (lines, bars, points)\n\nLayout (titles, axes, legend)\n\nYou don’t “draw” — you configure.\n\nInstallation (do this once)\npip install plotly\n\nOptional but common:\n\npip install pandas\n'

## plotly express

In [23]:
import plotly.express as px
import pandas as pd
import numpy as np

In [24]:
df = px.data.iris()

In [25]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [26]:
# scatter chart
fig = px.scatter(
    data_frame=df,
    x = 'sepal_length',
    y = 'sepal_width',
    color = 'species'
)
fig.show()

In [27]:
# Use cases:
# Used for relationships between variables.
# Correlation
# Clustering
# Outliers

In [28]:
df2 = px.data.stocks()

In [29]:
df2

           date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0    2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1    2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2    2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3    2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4    2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708
..          ...       ...       ...       ...       ...       ...       ...
100  2019-12-02  1.216280  1.546914  1.425061  1.075997  1.463641  1.720717
101  2019-12-09  1.222821  1.572286  1.432660  1.038855  1.421496  1.752239
102  2019-12-16  1.224418  1.596800  1.453455  1.104094  1.604362  1.784896
103  2019-12-23  1.226504  1.656000  1.521226  1.113728  1.567170  1.802472
104  2019-12-30  1.213014  1.678000  1.503360  1.098475  1.540883  1.788185

[105 rows x 7 columns]

In [30]:
# line chart => Mostly for time-series data.
# Key idea:Multiple columns → multiple lines automatically
fig = px.line(
    df2 ,
    x = 'date' ,
    y=['GOOG' , 'AAPL' , 'AMZN']
)
fig.show()

In [31]:
# bar chart => For categorical comparisons
# Common options:

# barmode="group"

# barmode="stack"

fig = px.bar(
    df,
    x = 'species',
    y = 'petal_length',
    color = 'species'

)
fig.show()

In [32]:
# histogram => For distributions.
fig = px.histogram(
    df,
    x = 'sepal_length',
    color = 'species',
    nbins = 20
)
fig.show()

In [33]:
# box plot => For spread & outliers.
fig = px.box(
    df , 
    x = 'species',
    y = 'petal_width',
    color = 'species'
)
fig.show()

In [34]:
# universal plotly parameters
fig = px.scatter(
    df , 
    x = 'sepal_length' , 
    y = 'sepal_width',
    color ='species',
    size = 'petal_width',
    hover_data=['petal_length'],
    title ='Flower Analysis'
)
fig.show()

In [35]:
# labels lets you rename things shown on the chart without changing your DataFrame.
# It controls:
# Axis titles
# Legend titles
# Hover labels
# Color bar titles

In [36]:
# labels
fig = px.scatter(
    df,
    x="sepal_width",
    y="sepal_length",
    color="species",
    size="petal_length",
    labels={
        "sepal_width": "Sepal Width (cm)",
        "sepal_length": "Sepal Length (cm)",
        "species": "Species",
        "petal_length": "Petal Length (cm)"
    }
)
fig.show()

In [37]:
# color bar => A color bar is shown only when color is a numeric column, not categorical.
import plotly.express as px

df = px.data.iris()

fig = px.scatter(
    df,
    x="sepal_width",
    y="sepal_length",
    color="petal_length",  # numeric column
    color_continuous_scale='viridis'
)
fig.show()

## Styling and Layout

In [38]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [39]:
# title and its position
fig = px.scatter(
    df,
    x = 'sepal_length',
    y = 'sepal_width'
)
fig.update_layout(
    title = 'SepalLength Vs Sepal Width',
    title_x = 0.5,
    title_y = 0.95,


)
fig.show()

In [40]:
# axis names
fig = px.scatter(
    df,
    x = 'sepal_length',
    y = 'sepal_width'
)
fig.update_layout(
    title = 'SepalLength Vs Sepal Width',
    title_x = 0.5,
    title_y = 0.95,

    xaxis_title='Sepal Length (cm)',
    yaxis_title = 'Sepal Width (cm)'

)
# you can also control ranges of x and y axis
fig.update_xaxes(range = [5,8])
fig.update_yaxes(range = [2,5])
fig.show()

In [41]:
# font and text size
fig = px.scatter(
    df,
    x = 'sepal_length',
    y = 'sepal_width'
)
fig.update_layout(
    title = 'SepalLength Vs Sepal Width',
    title_x = 0.5,
    title_y = 0.95,

    xaxis_title='Sepal Length (cm)',
    yaxis_title = 'Sepal Width (cm)',

    font = dict(family = 'Ariel',size = 18),
    title_font_size = 20

)
fig.show()

In [42]:
# backdround color and grid
fig = px.scatter(
    df,
    x = 'sepal_length',
    y = 'sepal_width'
)
fig.update_layout(
    title = 'SepalLength Vs Sepal Width',
    title_x = 0.5,
    title_y = 0.95,

    xaxis_title='Sepal Length (cm)',
    yaxis_title = 'Sepal Width (cm)',

    font = dict(family = 'Ariel',size = 18),
    
    plot_bgcolor = 'cyan',
    paper_bgcolor = 'green'

)
fig.show()

In [43]:
# gridlines

fig = px.scatter(
    df,
    x = 'sepal_length',
    y = 'sepal_width'
)
fig.update_layout(
    title = 'SepalLength Vs Sepal Width',
    title_x = 0.5,
    title_y = 0.95,


    xaxis_title='Sepal Length (cm)',
    yaxis_title = 'Sepal Width (cm)',

    font = dict(family = 'Ariel',size = 18),
    
      
    plot_bgcolor = 'cyan',
    paper_bgcolor = 'green',
)

fig.update_xaxes(showgrid = True , gridcolor = 'black')
fig.update_yaxes(showgrid = True , gridcolor = 'Yellow')
fig.show()

In [44]:
# legend control


fig = px.scatter(
    df,
    x = 'sepal_length',
    y = 'sepal_width'
)
fig.update_layout(
    title = 'SepalLength Vs Sepal Width',
    title_x = 0.5,
    title_y = 0.95,


    xaxis_title='Sepal Length (cm)',
    yaxis_title = 'Sepal Width (cm)',

    font = dict(family = 'Ariel',size = 18),
    
      
    plot_bgcolor = 'cyan',
    paper_bgcolor = 'green',

    legend_title_text = 'Species',
    legend = dict(
        orientation = 'h',
        yanchor = 'bottom'
    )
)

fig.update_xaxes(showgrid = True , gridcolor = 'black')
fig.update_yaxes(showgrid = True , gridcolor = 'Yellow')
fig.show()

## Graph Objects:

In [45]:
import plotly.graph_objects as go

In [69]:
# single trace
fig = go.Figure()

fig.add_trace(
    go.Scatter(
    x = [2,3,4,5],
    y = [5,6,7,8],
    mode = 'lines+markers',
    name = 'Line 1'
    )
)

fig.show()

In [70]:
#multiple traces
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x = [1,2,3],
        y = [4,5,6],
        name = 'Line 1'
    )
)

fig.add_trace(
    go.Scatter(
        x = [7,8,9,12],
        y = [4,5,6,7],
        name = "Name 2"
    )
)

fig.show()

In [83]:
# styling
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x = [1,2,3],
        y = [4,5,6],
        # name = 'Line 1',
        marker=dict(size = 14 , color = 'green' , symbol = 'circle'),
        line = dict(width = 3 , dash = 'solid'),
        name = "Styled Trace"
    )
)

fig.add_trace(
    go.Scatter(
        x = [7,8,9,12],
        y = [4,5,6,7],
        name = "Name 2"
    )
)


fig.show()

In [84]:
# subplots

In [ ]:
from plotly.subplots import make_subplots
dia = make_subplots(rows = 1 , cols = 2 , subplot_titles= ('Left' , 'Right'))

dia.add_trace(go.Scatter(x = [1,2,3] , y = [4,5,6]  , name = 'Fig 1') , row = 1, col= 1)
dia.add_trace(go.Scatter(x = [7,8,9] , y = [2,5,8] , name = 'Fig 2') , row = 1 , col = 2)

dia.show()