# Working with JSON

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_json(r"D:\Study\Data Science\Level 1\Data Analysis\Data Analysis Datasets\train (1).json")

In [5]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [24]:
df2 = pd.read_json(r'D:\Study\Data Science\Level 1\Data Analysis\Data Analysis Datasets\countries.json')
df2

,id,name,capital,region,subregion,population,area,currency,languages,timezones,callingCode,flag
0,1,India,New Delhi,Asia,Southern Asia,1428627663,3287263,"{'code': 'INR', 'name': 'Indian Rupee', 'symbo...","[Hindi, English]",[UTC+05:30],91,🇮🇳
1,2,United States,Washington D.C.,Americas,Northern America,331893745,9372610,"{'code': 'USD', 'name': 'US Dollar', 'symbol':...",[English],"[UTC-05:00, UTC-08:00]",1,🇺🇸
2,3,China,Beijing,Asia,Eastern Asia,1425671352,9596960,"{'code': 'CNY', 'name': 'Chinese Yuan', 'symbo...",[Mandarin],[UTC+08:00],86,🇨🇳
3,4,Brazil,Brasília,Americas,South America,214326223,8515767,"{'code': 'BRL', 'name': 'Brazilian Real', 'sym...",[Portuguese],[UTC-03:00],55,🇧🇷
4,5,Russia,Moscow,Europe,Eastern Europe,144713314,17098242,"{'code': 'RUB', 'name': 'Russian Ruble', 'symb...",[Russian],"[UTC+03:00, UTC+12:00]",7,🇷🇺
5,6,Germany,Berlin,Europe,Western Europe,83369843,357114,"{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}",[German],[UTC+01:00],49,🇩🇪
6,7,Japan,Tokyo,Asia,Eastern Asia,125681593,377930,"{'code': 'JPY', 'name': 'Japanese Yen', 'symbo...",[Japanese],[UTC+09:00],81,🇯🇵
7,8,Australia,Canberra,Oceania,Australia and New Zealand,25921000,7692024,"{'code': 'AUD', 'name': 'Australian Dollar', '...",[English],[UTC+10:00],61,🇦🇺
8,9,France,Paris,Europe,Western Europe,67817109,551695,"{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}",[French],[UTC+01:00],33,🇫🇷
9,10,South Africa,Pretoria,Africa,Southern Africa,59893885,1221037,"{'code': 'ZAR', 'name': 'South African Rand', ...","[Zulu, Xhosa, Afrikaans, English]",[UTC+02:00],27,🇿🇦

In [9]:
# from url
df2 = pd.read_json('https://jsonplaceholder.typicode.com/posts')

In [8]:
df2

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [11]:
df3 = pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
df3

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.0399
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.6920
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.9020
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,4.1100
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,2.6000
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.1820
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.2100
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.2800
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-09,1773014401,0.2800

In [17]:
df4 = pd.read_json('https://raw.githubusercontent.com/prust/wikipedia-movie-data/master/movies.json')
df4

,title,year,cast,genres,href,extract,thumbnail,thumbnail_width,thumbnail_height
0,After Dark in Central Park,1900,[],[],None,NaN,NaN,NaN,NaN
1,Boarding School Girls' Pajama Parade,1900,[],[],None,NaN,NaN,NaN,NaN
2,Buffalo Bill's Wild West Parad,1900,[],[],None,NaN,NaN,NaN,NaN
3,Caught,1900,[],[],None,NaN,NaN,NaN,NaN
4,Clowns Spinning Hats,1900,[],[Silent],Clowns_Spinning_Hats,Clowns Spinning Hats is a black-and-white sile...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
36268,Aquaman and the Lost Kingdom,2023,"[Jason Momoa, Amber Heard, Willem Dafoe, Patri...",[Superhero],Aquaman_and_the_Lost_Kingdom,Aquaman and the Lost Kingdom is an upcoming Am...,https://upload.wikimedia.org/wikipedia/en/thum...,320.0,163.0
36269,Untitled Ghostbusters: Afterlife sequel,2023,"[Mckenna Grace, Carrie Coon, Finn Wolfhard, Pa...","[Comedy, Supernatural]",Untitled_Ghostbusters:_Afterlife_sequel,The untitled Ghostbusters: Afterlife sequel is...,NaN,NaN,NaN
36270,Rebel Moon,2023,"[Sofia Boutella, Charlie Hunnam, Ray Fisher, D...",[Science Fiction],Rebel_Moon,Rebel Moon is an upcoming American epic space ...,NaN,NaN,NaN
36271,Migration,2023,[],[],Migration_(2023_film),This is a list of productions produced by Illu...,NaN,NaN,NaN
36272,The Color Purple,2023,"[Fantasia Barrino, Colman Domingo, Corey Hawki...","[Drama, Musical, Historical]",The_Color_Purple_(2023_film),The Color Purple is an upcoming American music...,NaN,NaN,NaN

# Working with SQL

In [21]:
!pip install pymysql

Collecting pymysql
  Using cached pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [22]:
import pymysql
from sqlalchemy import create_engine

In [47]:
engine = create_engine("mysql+pymysql://root:@localhost/world")
df = pd.read_sql("SELECT * FROM city" , engine )

In [48]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [49]:
engine = create_engine("mysql+pymysql://root:@localhost/world")
df = pd.read_sql("SELECT * FROM country" , engine )

In [50]:
df

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

# Working with Excel

In [41]:
df = pd.read_excel(r'D:\Study\Data Science\Level 1\Data Analysis\Data Analysis Datasets\business_dataset.xlsx')
df

        ID   Name  Age       City  Score
0        1  Karan   25    Chennai     63
1        2  Rahul   33      Delhi     99
2        3  Priya   33       Pune     72
3        4  Priya   23      Delhi     40
4        5  Priya   28      Delhi     72
...    ...    ...  ...        ...    ...
1995  1996  Sneha   39  Bangalore     80
1996  1997   Amit   22      Delhi     72
1997  1998  Priya   19  Bangalore     95
1998  1999   Neha   33       Pune     75
1999  2000  Priya   18    Chennai     83

[2000 rows x 5 columns]

In [44]:
# switching to differnt sheet
df = pd.read_excel(r'D:\Study\Data Science\Level 1\Data Analysis\Data Analysis Datasets\business_dataset.xlsx',sheet_name = 'Sales')
df

        ID   Product  Price  Quantity       City
0        1   Monitor  26773         8     Mumbai
1        2  Keyboard  47652         7       Pune
2        3   Monitor  10369        19     Mumbai
3        4    Laptop  39464         7  Bangalore
4        5   Monitor  25617         2      Delhi
...    ...       ...    ...       ...        ...
1795  1796     Mouse  51545        17     Mumbai
1796  1797     Mouse  45281        10     Mumbai
1797  1798   Printer   1570         1       Pune
1798  1799  Keyboard  14589         4  Bangalore
1799  1800   Monitor  14823        20       Pune

[1800 rows x 5 columns]

# Working with txt files

In [38]:
# YOU USE READ_CSV BUT CHANGE THE SEP PARAMETER ACCORDING TO THE TXT FILE
df = pd.read_csv(r"D:\Study\Data Science\Level 1\Data Analysis\Data Analysis Datasets\sample_dataset.txt",sep = ' ')

In [39]:
df

,ID,Name,Age,City,Score,1,Ravi,22,Mumbai,87,2,Neha,32,Mumbai.1,73,3,Amit,35
0,Delhi,56,4,Sneha,32,Delhi,54,5,Ravi,25,Hyderabad,76,6,Neha,29,Mumbai,88,NaN
1,7,Karan,35,Bangalore,85,8,Rahul,35,Chennai,59,9,Ravi,28,Delhi,73,10,NaN,NaN
2,Priya,34,Mumbai,57,11,Neha,19,Ahmedabad,71,12,Neha,19,Bangalore,83,13,NaN,NaN,NaN
3,Karan,21,Chennai,54,14,Pooja,30,Kolkata,100,15,Karan,21,Chennai,75,16,NaN,NaN,NaN
4,Neha,24,Ahmedabad,91,17,Vikram,23,Mumbai,48,18,Pooja,22,Mumbai,59,19,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1734,32,Kolkata,68,4989,Ankit,33,Bangalore,89,4990,Ravi,34,Bangalore,97,4991,NaN,NaN,NaN,NaN
1735,Priya,29,Delhi,41,4992,Amit,19,Ahmedabad,90,4993,Neha,26,Pune,41,4994,NaN,NaN,NaN
1736,Vikram,32,Mumbai,45,4995,Pooja,28,Mumbai,95,4996,Amit,33,Hyderabad,54,NaN,NaN,NaN,NaN
1737,4997,Sneha,35,Bangalore,78,4998,Ankit,18,Delhi,65,4999,Priya,23,Delhi,96,NaN,NaN,NaN
1738,5000,Pooja,30,Pune,72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN