## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [ ]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [ ]:
# code here

In [ ]:
titanic_df.groupby('Pclass')['Age'].mean()

NameError: name 'titanic_df' is not defined

In [ ]:
titanic_df.groupby('Pclass')['Age'].apply(lambda x: x.isnull().sum())

NameError: name 'titanic_df' is not defined

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [ ]:
# code here

In [ ]:
titanic_df.groupby('Pclass')['Embarked'].apply(lambda x : x.isnull().sum())

NameError: name 'titanic_df' is not defined

In [ ]:
value_to_fill_missing_values = titanic_df.groupby('Pclass')['Embarked'].apply(lambda x : x.mode()).reset_index()['Embarked'].mode().values.item()

NameError: name 'titanic_df' is not defined

In [ ]:
titanic_df['Embarked'] = titanic_df.groupby('Pclass')['Embarked'].transform(lambda x: x.fillna(value_to_fill_missing_values))

NameError: name 'titanic_df' is not defined

In [ ]:
titanic_df.groupby('Pclass')['Embarked'].apply(lambda x : x.isnull().sum())

NameError: name 'titanic_df' is not defined

In [ ]:
titanic_df.groupby('Pclass')['Embarked'].apply(lambda x : x.value_counts())

NameError: name 'titanic_df' is not defined

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [ ]:
# code here

In [ ]:
titanic_df.head()

NameError: name 'titanic_df' is not defined

In [ ]:
(titanic_df.groupby(['Embarked','Pclass']))['Fare'].mean()

NameError: name 'titanic_df' is not defined

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [2]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [ ]:
fifa_df.head()

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [ ]:
# code here

In [3]:
def z_normalization(group, cols_to_perform):
    for col in cols_to_perform:
        mean = group[col].mean()
        std = group[col].std()
        group[col] = (group[col] - mean) / std
    return group

In [4]:
cols_to_normalize = [
    "Passes",
    "Passes Completed",
    "Attempted Line Breaks",
    "Completed Line Breaks"
]

normalized_df = (
    fifa_df
    .groupby("Team", group_keys=False)
    .apply(z_normalization, cols_to_perform=cols_to_normalize)
)

/tmp/ipython-input-3120976139.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(z_normalization, cols_to_perform=cols_to_normalize)

In [7]:
team_stats = fifa_df.groupby("Team").agg(
    min_passes=("Passes", "min"),
    max_passes=("Passes", "max"),
    min_yellow_cards=("Yellow Cards", "min"),
    max_yellow_cards=("Yellow Cards", "max"),
    avg_yellow_cards=("Yellow Cards", "mean"),
    max_attempted_line_breaks=("Attempted Line Breaks", "max"),
    min_attempted_line_breaks=("Attempted Line Breaks", "min"),
    std_attempted_line_breaks=("Attempted Line Breaks", "std"),
    avg_possession=("Possession (%)", "mean")
).reset_index()

In [8]:
print(team_stats)

              Team  min_passes  max_passes  min_yellow_cards  \
0        Argentina         408         862                 0
1        Australia         286         466                 0
2          Belgium         512         685                 1
3           Brazil         548         695                 0
4         Cameroon         295         500                 1
5           Canada         448         536                 2
6       Costa Rica         231         454                 1
7          Croatia         461         724                 0
8          Denmark         537         650                 1
9          Ecuador         429         484                 0
10         England         508         810                 0
11          France         358         734                 0
12         Germany         352         827                 0
13           Ghana         319         460                 2
14            Iran         232         463                 2
15           Japan         225         591                 0
16  Korea Republic         359         548                 1
17          Mexico         356         500                 1
18         Morocco         229         583                 0
19     Netherlands         403         786                 0
20          Poland         303         466                 1
21        Portugal         461         678                 0
22           Qatar         424         457                 0
23    Saudi Arabia         267         560                 2
24         Senegal         277         511                 1
25          Serbia         403         513                 2
26           Spain         647        1070                 0
27     Switzerland         403         512                 1
28         Tunisia         328         501                 1
29   United States         427         572                 0
30         Uruguay         390         528                 1
31           Wales         325         508                 1

    max_yellow_cards  avg_yellow_cards  max_attempted_line_breaks  \
0                  8          2.285714                        249
1                  3          1.750000                        171
2                  3          1.666667                        195
3                  3          1.200000                        193
4                  5          2.666667                        182
5                  4          2.666667                        176
6                  3          2.000000                        154
7                  2          1.142857                        259
8                  2          1.666667                        241
9                  2          1.000000                        177
10                 1          0.200000                        208
11                 3          1.142857                        179
12                 3          1.000000                        256
13                 4          2.666667                        188
14                 3          2.333333                        195
15                 3          1.500000                        253
16                 2          1.500000                        201
17                 4          2.333333                        198
18                 3          1.285714                        157
19                 4          1.800000                        198
20                 3          1.750000                        156
21                 3          1.200000                        197
22                 4          2.333333                        174
23                 6          4.666667                        205
24                 3          1.750000                        184
25                 7          4.000000                        184
26                 1          0.500000                        237
27                 4          2.250000                        178
28                 3          1.666667                        200
29                 4          1.250000                        204
30                 3          2.000000                        186
31                 2          1.666667                        208

    min_attempted_line_breaks  std_attempted_line_breaks  avg_possession
0                         141                  38.774685       49.285714
1                         133                  17.682383       31.250000
2                         167                  14.422205       49.000000
3                         164                  10.691118       50.400000
4                         144                  19.857828       38.333333
5                         102                  37.753587       44.333333
6                          86                  38.974351       27.333333
7                          97                  54.499891       47.428571
8                         173                  34.000000       51.333333
9                         143                  17.009801       42.666667
10                        133                  29.676590       57.200000
11                        126                  21.407609       44.857143
12                        143                  56.624494       53.000000
13                        122                  33.020196       37.000000
14                         56                  77.526340       31.666667
15                        104                  64.048810       30.250000
16                        139                  27.072434       42.250000
17                        127                  40.706265       46.666667
18                        128                  10.641339       34.285714
19                        168                  12.759310       44.000000
20                         79                  36.326070       32.000000
21                        165                  13.049904       53.800000
22                        159                   7.767453       39.333333
23                        147                  29.022979       36.666667
24                        143                  16.938615       38.500000
25                        140                  22.188586       42.666667
26                        186                  24.289916       67.000000
27                        157                   9.032349       43.000000
28                        153                  24.419937       38.666667
29                        143                  27.693260       47.000000
30                        146                  22.030282       41.000000
31                        104                  53.028294       41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [ ]:
# code here

In [ ]:
ball = pd.read_csv('/content/18_ipl_deliveries.csv')

In [ ]:
ball.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [ ]:
temp = ball[ball['innings'] == 2]

In [ ]:
temp.groupby('batter')['batsman_run'].sum().sort_values(ascending=False).head(1).index.item()

'V Kohli'

In [ ]:
runsWhileChasing = temp.groupby('batter')['batsman_run'].sum().sort_index()

In [ ]:
BallFaced = temp.groupby('batter')['ballnumber'].count().sort_index()

In [ ]:
BallFaced = BallFaced[BallFaced > 100]

In [ ]:
strike_rate = (runsWhileChasing / BallFaced) * 100

In [ ]:
strike_rate = strike_rate.sort_values(ascending=False)

In [ ]:
strike_rate.dropna(inplace=True)

In [ ]:
strike_rate

batter
PJ Cummins        186.554622
LS Livingstone    163.963964
AD Russell        162.975207
SP Narine         159.308511
V Sehwag          157.505519
                     ...
LR Shukla          91.946309
R Dhawan           90.196078
GH Vihari          89.500000
B Kumar            89.285714
K Goel             79.508197
Length: 184, dtype: float64

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [ ]:
# code here

In [ ]:
ball.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [ ]:
temp = ball[ball['isWicketDelivery'] == 1]

In [ ]:
most_bower_batsman_wickets = temp.groupby(['bowler','player_out'])['ID'].count().sort_values(ascending=False).head(7)

In [ ]:
type(most_bower_batsman_wickets)

pandas.core.series.Series

In [ ]:
most_bower_batsman_wickets = most_bower_batsman_wickets.reset_index()

In [ ]:
def runs_concluded(bowler , batter):

  runs = ball[ ( ball['bowler'] == bowler ) & (ball['batter'] == batter)]['batsman_run'].sum()

  return runs

In [ ]:
most_bower_batsman_wickets

           bowler  player_out  ID
0          Z Khan    MS Dhoni   7
1       RA Jadeja  GJ Maxwell   7
2        R Ashwin  RV Uthappa   7
3         PP Ojha    MS Dhoni   7
4        A Mishra   RG Sharma   7
5       SP Narine   RG Sharma   7
6  Sandeep Sharma     V Kohli   7

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [ ]:
# code here

In [ ]:
ball.groupby(['batter','non-striker'])['batsman_run'].sum().sort_values(ascending = False ).reset_index().head(1)

           batter non-striker  batsman_run
0  AB de Villiers     V Kohli         1566

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [ ]:
# code here

In [ ]:
played_together = ball.groupby(['batter','non-striker'])['batsman_run'].sum()

In [ ]:
played_together = played_together[played_together > 0]

In [ ]:
df = played_together.reset_index()

In [ ]:
balles_played = ball.groupby('batter')['batsman_run'].count()

In [ ]:
runs_scored = ball.groupby('batter')['batsman_run'].sum()

In [ ]:
strike_rate = ( runs_scored/balles_played ) * 100

In [ ]:
ball

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [ ]:
import numpy as np

In [ ]:
no_times_get_out = ball.groupby('player_out')['batsman_run'].count()

In [ ]:
avg = runs_scored / no_times_get_out

In [ ]:
avg

A Ashish Reddy    18.666667
A Badoni          20.125000
A Chandila              NaN
A Chopra           8.833333
A Choudhary       25.000000
                    ...
Yash Dayal         0.000000
Yashpal Singh     11.750000
Younis Khan        3.000000
Yuvraj Singh      24.810811
Z Khan             8.357143
Name: batsman_run, Length: 606, dtype: float64

In [ ]:
df['strike_rate'] = strike_rate

In [ ]:
df['avg'] = avg

In [ ]:
df

              batter      non-striker  batsman_run  strike_rate  avg
0     A Ashish Reddy         A Mishra           19          NaN  NaN
1     A Ashish Reddy  AA Jhunjhunwala            3          NaN  NaN
2     A Ashish Reddy         CL White            3          NaN  NaN
3     A Ashish Reddy     DB Ravi Teja            6          NaN  NaN
4     A Ashish Reddy        DJG Sammy           26          NaN  NaN
...              ...              ...          ...          ...  ...
7397          Z Khan    R Vinay Kumar           13          NaN  NaN
7398          Z Khan         S Nadeem            3          NaN  NaN
7399          Z Khan       SL Malinga           17          NaN  NaN
7400          Z Khan     SR Tendulkar            2          NaN  NaN
7401          Z Khan        SS Tiwary           21          NaN  NaN

[7402 rows x 5 columns]